from curses.ascii import SUB
from re import S
from django.db import models

# Create your models here.


class Survey(models.Model):
    # models for the html front end survey inputs
    objects = models.Manager()
    gender = models.TextField()
    ethnicity = models.TextField()
    grade = models.TextField()
    major = models.TextField()
    discussion = models.TextField()
    gpa = models.TextField()
    program = models.TextField()
    professional = models.TextField()
    enrollment = models.TextField()
    prior = models.TextField()
    internship = models.BooleanField()
    research = models.BooleanField()
    parent_engineer = models.BooleanField()
    family_engineer = models.BooleanField()
    previous_school_impact = models.TextField()
    finish_degree = models.TextField()
    finish_degree_here = models.TextField()
    technology_importance = models.TextField()
    parents_disprove_difft = models.TextField()
    engineer_fix_world = models.TextField()
    engineer_paid = models.TextField()
    parents_want = models.TextField()
    job_guarantee = models.TextField()
    faculty_encor = models.TextField()
    mentor_encor = models.TextField()
    intro_opportunity = models.TextField()
    feel_good = models.TextField()
    like_build = models.TextField()
    engineer_fun = models.TextField()
    use_society = models.TextField()
    engineer_interesting = models.TextField()
    figure_out_work = models.TextField()
    mentoring_program = models.TextField()
    Relate = models.TextField()
    lot_common = models.TextField()
    others_share = models.TextField()
    relate_extra = models.TextField()
    succeed = models.TextField()
    well_paying = models.TextField()
    expect = models.TextField()
    lifestyle = models.TextField()
    part_group = models.TextField()
    job = models.TextField()
    like_job = models.TextField()
    bad_test = models.TextField()
    friends = models.TextField()
    cope = models.TextField()
    only_one = models.TextField()
    approach = models.TextField()
    new_env = models.TextField()
    self_confidence = models.TextField()
    leadership = models.TextField()
    public = models.TextField()
    math = models.TextField()
    science = models.TextField()
    communication = models.TextField()
    apply = models.TextField()
    business = models.TextField()
    teams = models.TextField()
    reward = models.TextField()
    study = models.TextField()
    advantage = models.TextField()
    no_care = models.TextField()
    benefit = models.TextField()
    other = models.TextField()
    no_change = models.TextField()
    effort = models.TextField()
    boring = models.TextField()

class Results(models.Model):
    # models for the html front end survey results
    score_1 = (Survey.engineer_paid + Survey.well_paying + Survey.job_guarantee) / (3*4)
    score_2 = (Survey.parents_disprove_difft + Survey.parents_want) / (2*4)
    score_3 = (Survey.technology_importance + Survey.engineer_fix_world + Survey.use_society) / (3*4)
    score_4 = (Survey.faculty_encor + Survey.mentor_encor + Survey.mentoring_program) / (3*4)
    score_5 = (Survey.feel_good + Survey.engineer_fun + Survey.engineer_interesting) / (3*4)
    score_6 = (Survey.like_build + Survey.figure_out_work) / (2*4)
    score_7 = (Survey.self_confidence + Survey.leadership + Survey.public + Survey.communication + Survey.business + Survey.teams) / (6*4)
    score_8 = (Survey.math + Survey.science + Survey.apply) / (3*4)
    score_9 = (Survey.succeed + Survey.job + Survey.intro_opportunity + Survey.lifestyle + Survey.part_group + Survey.like_job) / (6*4)
    score_10 = (Survey.relate_extra + Survey.friends + Survey.engineer_interesting) / (3*4)
    score_11 = (Survey.cope + Survey.friends + Survey.new_env + Survey.discussion) / (4*4)
    score_12 = (Survey.reward + Survey.study + Survey.advantage + Survey.boring) / (4*4)
    score_13 = (Survey.technology_importance + Survey.self_confidence + Survey.lot_common) / (3*4)
    score_14 = (Survey.mentor_encor) / (1*4)
    eps_total = (score_1 + score_2 + score_3) / 3
    spve = (score_4 + score_5 + score_6 + score_7 + score_8 + score_9 + score_10) / 7
    me = (score_11 + score_12 + score_13 + score_14) / 4
