# Generated by Django 4.0.4 on 2022-04-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField()),
                ('ethnicity', models.TextField()),
                ('grade', models.TextField()),
                ('major', models.TextField()),
                ('discussion', models.TextField()),
                ('gpa', models.TextField()),
                ('program', models.TextField()),
                ('professional', models.TextField()),
                ('enrollment', models.TextField()),
                ('prior', models.TextField()),
                ('internship', models.BooleanField()),
                ('research', models.BooleanField()),
                ('parent_engineer', models.BooleanField()),
                ('family_engineer', models.BooleanField()),
            ],
        ),
    ]
